version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: arkeon325
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s webrick -b '0.0.0.0'
    volumes:
      - .:/rails-docker
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: magnomatos822@gmail.com
      PGADMIN_DEFAULT_PASSWORD: PgAdmin2019!
    ports:
      - "16543:80"
    depends_on:
      - db
    
volumes:
  pgdata: